name: Bug Report
description: Report a bug to echarts-enhanced-completion
title: "[Bug] "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      The issue is reserved exclusively for bug reports.

      Also try to search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue using the form below instead of commenting on the old issue.

      For usage questions about echarts, please use the following resources:

      - Read the [docs](https://echarts.apache.org/option.html)
      - Find in [examples](https://echarts.apache.org/examples/)
      - Look for / ask questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/echarts)

- type: input
  attributes:
    label: Version
    description: |
      Check if the issue is reproducible with the latest stable version.
    placeholder: |
      e.g. 1.3.9

  validations:
    required: true

- type: dropdown
  attributes:
    label: File type
    description: |
      What type of file are you using?
    options:
      - html
      - javascript
      - typescript
      - vue

  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      What do we need to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.

    placeholder: |
      1. How do you create the option.
      2. User interactions before the error happens.

  validations:
    required: true

- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      e.g.
        - **OS**: Windows 10
    value: |
        - **OS**:
    render: markdown

  validations:
    required: false

- type: textarea
  attributes:
    label: Any additional comments?
    description: |
      e.g. some background/context of how you ran into this bug.

  validations:
    required: false