name: Feature Request
description: Request a new feature from echarts-enhanced-completion
title: "[Feature] "
labels: [feature]
body:
- type: markdown
  attributes:
    value: |
      The issue is reserved exclusively for feature requests.

      Also try to search for your issue - it may have already been answered in the development branch.

- type: textarea
  attributes:
    label: What problem does this feature solve?
    description: |
      Explain your use case, context, and rationale behind this feature request. More importantly, what is the end user experience you are trying to build that led to the need for this feature?

  validations:
    required: true